version: "3.9"

services:
  backend:
    build:
      context: .   
    ports:
      - "8000:8000"  
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./front/front  
    ports:
      - "4200:80" 
